"""agrega_modelo_transdisciplinario_y_ai

Revision ID: 290b77d4bffb
Revises: 7e09cb887c4e
Create Date: 2026-09-26 22:21:23.439496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '290b77d4bffb'
down_revision: Union[str, Sequence[str], None] = '7e09cb887c4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedback_recomendaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recomendacion_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('tipo_feedback', sa.String(length=50), nullable=False),
    sa.Column('comentario', sa.Text(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['recomendacion_id'], ['recomendaciones_ia.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedback_recomendaciones_id'), 'feedback_recomendaciones', ['id'], unique=False)
    op.add_column('alertas_bienestar', sa.Column('regla_activada', sa.String(length=100), nullable=False))
    op.alter_column('alertas_bienestar', 'usuario_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('alertas_bienestar', 'tipo',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('alertas_bienestar', 'nivel',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('alertas_bienestar', 'titulo',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('alertas_bienestar', 'descripcion',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               nullable=False)
    op.alter_column('alertas_bienestar', 'recomendacion',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               nullable=False)
    op.alter_column('alertas_bienestar', 'disciplinas',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('alertas_bienestar', 'fecha_creacion',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('auditoria_ia', 'modulo',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('auditoria_ia', 'accion',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('auditoria_ia', 'estado',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('auditoria_ia', 'fecha_creacion',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.drop_column('auditoria_ia', 'tiempo_respuesta_ms')
    op.add_column('conversaciones_chat', sa.Column('titulo', sa.String(length=150), nullable=True))
    op.alter_column('conversaciones_chat', 'usuario_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('conversaciones_chat', 'fecha_creacion',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('mensajes_chat', 'conversacion_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('mensajes_chat', 'emisor',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('mensajes_chat', 'contenido',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               nullable=False)
    op.alter_column('mensajes_chat', 'disciplinas',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('mensajes_chat', 'fecha_creacion',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('recomendaciones_ia', 'usuario_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('recomendaciones_ia', 'categoria',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('recomendaciones_ia', 'prioridad',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('recomendaciones_ia', 'titulo',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('recomendaciones_ia', 'contenido',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               nullable=False)
    op.alter_column('recomendaciones_ia', 'disciplinas',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('recomendaciones_ia', 'disclaimer',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               nullable=False)
    op.alter_column('recomendaciones_ia', 'fecha_creacion',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.drop_column('recomendaciones_ia', 'calificacion_utilidad')
    op.add_column('registros_bienestar', sa.Column('comidas_realizadas', sa.Integer(), nullable=True))
    op.add_column('registros_bienestar', sa.Column('vasos_agua', sa.Integer(), nullable=True))
    op.add_column('registros_bienestar', sa.Column('minutos_actividad_fisica', sa.Integer(), nullable=True))
    op.add_column('registros_bienestar', sa.Column('nivel_energia', sa.Integer(), nullable=True))
    op.add_column('registros_bienestar', sa.Column('nivel_animo', sa.Integer(), nullable=True))
    op.add_column('registros_bienestar', sa.Column('emociones_predominantes', sa.String(length=200), nullable=True))
    op.add_column('registros_bienestar', sa.Column('nivel_concentracion', sa.Integer(), nullable=True))
    op.add_column('registros_bienestar', sa.Column('rendimiento_percibido', sa.Integer(), nullable=True))
    op.add_column('registros_bienestar', sa.Column('pausas_estudio', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('registros_bienestar', 'pausas_estudio')
    op.drop_column('registros_bienestar', 'rendimiento_percibido')
    op.drop_column('registros_bienestar', 'nivel_concentracion')
    op.drop_column('registros_bienestar', 'emociones_predominantes')
    op.drop_column('registros_bienestar', 'nivel_animo')
    op.drop_column('registros_bienestar', 'nivel_energia')
    op.drop_column('registros_bienestar', 'minutos_actividad_fisica')
    op.drop_column('registros_bienestar', 'vasos_agua')
    op.drop_column('registros_bienestar', 'comidas_realizadas')
    op.add_column('recomendaciones_ia', sa.Column('calificacion_utilidad', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('recomendaciones_ia', 'fecha_creacion',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('recomendaciones_ia', 'disclaimer',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               nullable=True)
    op.alter_column('recomendaciones_ia', 'disciplinas',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('recomendaciones_ia', 'contenido',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               nullable=True)
    op.alter_column('recomendaciones_ia', 'titulo',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('recomendaciones_ia', 'prioridad',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('recomendaciones_ia', 'categoria',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('recomendaciones_ia', 'usuario_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('mensajes_chat', 'fecha_creacion',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('mensajes_chat', 'disciplinas',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('mensajes_chat', 'contenido',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               nullable=True)
    op.alter_column('mensajes_chat', 'emisor',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('mensajes_chat', 'conversacion_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('conversaciones_chat', 'fecha_creacion',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('conversaciones_chat', 'usuario_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('conversaciones_chat', 'titulo')
    op.add_column('auditoria_ia', sa.Column('tiempo_respuesta_ms', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.alter_column('auditoria_ia', 'fecha_creacion',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('auditoria_ia', 'estado',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('auditoria_ia', 'accion',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('auditoria_ia', 'modulo',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('alertas_bienestar', 'fecha_creacion',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('alertas_bienestar', 'disciplinas',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('alertas_bienestar', 'recomendacion',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               nullable=True)
    op.alter_column('alertas_bienestar', 'descripcion',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               nullable=True)
    op.alter_column('alertas_bienestar', 'titulo',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('alertas_bienestar', 'nivel',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('alertas_bienestar', 'tipo',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('alertas_bienestar', 'usuario_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('alertas_bienestar', 'regla_activada')
    op.drop_index(op.f('ix_feedback_recomendaciones_id'), table_name='feedback_recomendaciones')
    op.drop_table('feedback_recomendaciones')
    # ### end Alembic commands ###
