"""agrega ciclo a users

Revision ID: 4219d9b48047
Revises: f91690b9b3a9
Create Date: 2026-09-15 14:50:15.591365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4219d9b48047'
down_revision: Union[str, Sequence[str], None] = 'f91690b9b3a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('ciclo', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'ciclo')
    # ### end Alembic commands ###
