"""make_actividad_fisica_nullable

Revision ID: 46dcc13d1d54
Revises: ef8d4d6993c0
Create Date: 2026-09-15 00:23:13.104199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46dcc13d1d54'
down_revision: Union[str, Sequence[str], None] = 'ef8d4d6993c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'registros_bienestar',
        'actividad_fisica',
        existing_type=sa.INTEGER(),  # o el tipo anterior que aparezca allí
        type_=sa.Boolean(),
        nullable=True,
        postgresql_using='actividad_fisica::boolean'  # <--- Agrega esta línea
    )
    # ### end Alembic commands ###

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('registros_bienestar', 'actividad_fisica',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
