"""add_validacion

Revision ID: 5d7b898a1dbb
Revises: 290b77d4bffb
Create Date: 2026-09-27 16:37:34.479939

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d7b898a1dbb'
down_revision: Union[str, Sequence[str], None] = '290b77d4bffb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('validaciones_especialista',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('especialista_id', sa.Integer(), nullable=False),
    sa.Column('recomendacion_id', sa.Integer(), nullable=True),
    sa.Column('alerta_id', sa.Integer(), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=False),
    sa.Column('observacion', sa.Text(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['alerta_id'], ['alertas_bienestar.id'], ),
    sa.ForeignKeyConstraint(['especialista_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['recomendacion_id'], ['recomendaciones_ia.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_validaciones_especialista_id'), 'validaciones_especialista', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_validaciones_especialista_id'), table_name='validaciones_especialista')
    op.drop_table('validaciones_especialista')
    # ### end Alembic commands ###
