"""agrega is_active a users

Revision ID: 621920eec14c
Revises: 46dcc13d1d54
Create Date: 2026-09-15 14:38:51.682472

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '621920eec14c'
down_revision: Union[str, Sequence[str], None] = '46dcc13d1d54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('registros_bienestar', sa.Column('tipo_actividad', sa.String(), nullable=True))
    op.add_column('registros_bienestar', sa.Column('alimentacion_resumen', sa.String(), nullable=True))
    op.add_column('registros_bienestar', sa.Column('emociones', sa.String(), nullable=True))
    op.add_column('registros_bienestar', sa.Column('nivel_concentracion', sa.Integer(), nullable=True))
    op.add_column('registros_bienestar', sa.Column('rendimiento_percibido', sa.Integer(), nullable=True))
    op.alter_column('registros_bienestar', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('registros_bienestar', 'fecha',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.create_index(op.f('ix_registros_bienestar_user_id'), 'registros_bienestar', ['user_id'], unique=False)
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.drop_column('users', 'ciclo')
    op.drop_column('users', 'fecha_creacion')
    op.drop_column('users', 'rol')
    op.drop_column('users', 'nombre')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('nombre', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('rol', postgresql.ENUM('estudiante', 'docente', 'admin', name='roleenum'), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('fecha_creacion', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('ciclo', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('users', 'is_active')
    op.drop_index(op.f('ix_registros_bienestar_user_id'), table_name='registros_bienestar')
    op.alter_column('registros_bienestar', 'fecha',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('registros_bienestar', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('registros_bienestar', 'rendimiento_percibido')
    op.drop_column('registros_bienestar', 'nivel_concentracion')
    op.drop_column('registros_bienestar', 'emociones')
    op.drop_column('registros_bienestar', 'alimentacion_resumen')
    op.drop_column('registros_bienestar', 'tipo_actividad')
    # ### end Alembic commands ###
