"""Agrega modelos de IA

Revision ID: 7e09cb887c4e
Revises: d0f97caa721b
Create Date: 2026-09-25 21:29:57.582180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e09cb887c4e'
down_revision: Union[str, Sequence[str], None] = 'd0f97caa721b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alertas_bienestar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.String(), nullable=True),
    sa.Column('nivel', sa.String(), nullable=True),
    sa.Column('titulo', sa.String(), nullable=True),
    sa.Column('descripcion', sa.String(), nullable=True),
    sa.Column('recomendacion', sa.String(), nullable=True),
    sa.Column('disciplinas', sa.JSON(), nullable=True),
    sa.Column('requiere_apoyo_profesional', sa.Boolean(), nullable=True),
    sa.Column('leida', sa.Boolean(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alertas_bienestar_id'), 'alertas_bienestar', ['id'], unique=False)
    op.create_table('auditoria_ia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('modulo', sa.String(), nullable=True),
    sa.Column('accion', sa.String(), nullable=True),
    sa.Column('estado', sa.String(), nullable=True),
    sa.Column('tiempo_respuesta_ms', sa.Float(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auditoria_ia_id'), 'auditoria_ia', ['id'], unique=False)
    op.create_table('conversaciones_chat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('estado', sa.String(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversaciones_chat_id'), 'conversaciones_chat', ['id'], unique=False)
    op.create_table('recomendaciones_ia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('categoria', sa.String(), nullable=True),
    sa.Column('prioridad', sa.String(), nullable=True),
    sa.Column('titulo', sa.String(), nullable=True),
    sa.Column('contenido', sa.String(), nullable=True),
    sa.Column('disciplinas', sa.JSON(), nullable=True),
    sa.Column('disclaimer', sa.String(), nullable=True),
    sa.Column('estado', sa.String(), nullable=True),
    sa.Column('calificacion_utilidad', sa.String(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recomendaciones_ia_id'), 'recomendaciones_ia', ['id'], unique=False)
    op.create_table('mensajes_chat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversacion_id', sa.Integer(), nullable=True),
    sa.Column('emisor', sa.String(), nullable=True),
    sa.Column('contenido', sa.String(), nullable=True),
    sa.Column('disciplinas', sa.JSON(), nullable=True),
    sa.Column('requiere_apoyo_profesional', sa.Boolean(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['conversacion_id'], ['conversaciones_chat.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mensajes_chat_id'), 'mensajes_chat', ['id'], unique=False)
    op.alter_column('registros_bienestar', 'usuario_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('registros_bienestar', 'actividad_fisica',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index(op.f('ix_registros_bienestar_usuario_id'), table_name='registros_bienestar')
    op.drop_column('registros_bienestar', 'emociones')
    op.drop_column('registros_bienestar', 'tipo_actividad')
    op.drop_column('registros_bienestar', 'nivel_concentracion')
    op.drop_column('registros_bienestar', 'rendimiento_percibido')
    op.drop_column('registros_bienestar', 'alimentacion_resumen')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('registros_bienestar', sa.Column('alimentacion_resumen', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('registros_bienestar', sa.Column('rendimiento_percibido', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('registros_bienestar', sa.Column('nivel_concentracion', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('registros_bienestar', sa.Column('tipo_actividad', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('registros_bienestar', sa.Column('emociones', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_registros_bienestar_usuario_id'), 'registros_bienestar', ['usuario_id'], unique=False)
    op.alter_column('registros_bienestar', 'actividad_fisica',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('registros_bienestar', 'usuario_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_mensajes_chat_id'), table_name='mensajes_chat')
    op.drop_table('mensajes_chat')
    op.drop_index(op.f('ix_recomendaciones_ia_id'), table_name='recomendaciones_ia')
    op.drop_table('recomendaciones_ia')
    op.drop_index(op.f('ix_conversaciones_chat_id'), table_name='conversaciones_chat')
    op.drop_table('conversaciones_chat')
    op.drop_index(op.f('ix_auditoria_ia_id'), table_name='auditoria_ia')
    op.drop_table('auditoria_ia')
    op.drop_index(op.f('ix_alertas_bienestar_id'), table_name='alertas_bienestar')
    op.drop_table('alertas_bienestar')
    # ### end Alembic commands ###
