"""agrega rol a users

Revision ID: d0f97caa721b
Revises: 4219d9b48047
Create Date: 2026-09-15 14:53:22.052208

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0f97caa721b'
down_revision: Union[str, Sequence[str], None] = '4219d9b48047'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Modifica la línea para que quede exactamente así:
op.add_column('users', sa.Column('rol', sa.String(), nullable=False, server_default='estudiante'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'rol')
    # ### end Alembic commands ###
