"""agrega nombre a users

Revision ID: f91690b9b3a9
Revises: 621920eec14c
Create Date: 2026-09-15 14:42:41.051149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f91690b9b3a9'
down_revision: Union[str, Sequence[str], None] = '621920eec14c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('nombre', sa.String(), nullable=False, server_default='Usuario'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'nombre')
    # ### end Alembic commands ###
